server:
  port: 8081

kafka:
  groupId: myGroup
  concurrencyCount: 3
  address: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}


redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

cache-minute:
  event-cache-hour: 1